[theme]
# Cor de fundo principal (Escuro/Gráfite do painel)
backgroundColor = "#111418"

# Cor de fundo dos blocos secundários e da barra lateral (Sidebar)
secondaryBackgroundColor = "#1c2026"

# Cor dos textos principais (Branco/Cinza claro de alta leitura)
textColor = "#f1f3f5"

# Cor de destaque (O Verde do gráfico gauge e do logo IBAMA MMA)
primaryColor = "#4d6b53"

# Fonte padrão limpa
font = "sans serif"
